### ISSUE TITLE
MUC Invite problem in the recent versions.

### ISSUE THREAD

**Issue by nandinibhaduri** [jcbrand/converse.js#1024]
The MUC invitation doesn't come show in recent version. I am using dist/converse.js and view_mode: 'fullscreen'. But it works as expected using - 3.2.1/dist/inverse.js.

Here is the javascript error I am getting.

```
converse.js:39333  FATAL: TypeError: Cannot read property 'getAttribute' of null
    at Object._converse.onDirectMUCInvitation (https://cdn.conversejs.org/dist/converse.js:54518:29)
    at Strophe.Handler.handler (https://cdn.conversejs.org/dist/converse.js:54552:23)
    at Strophe.Handler.run (https://cdn.conversejs.org/dist/converse.js:32015:27)
    at https://cdn.conversejs.org/dist/converse.js:33275:34
    at Object.forEachChild (https://cdn.conversejs.org/dist/converse.js:30983:17)
    at Strophe.Connection._dataRecv (https://cdn.conversejs.org/dist/converse.js:33263:17)
    at Strophe.Bosh._onRequestStateChange (https://cdn.conversejs.org/dist/converse.js:34972:13)
_converse.log @ converse.js:39333
Strophe.log @ converse.js:40860
fatal @ converse.js:31552
_handleError @ converse.js:31456
run @ converse.js:32017
(anonymous) @ converse.js:33275
forEachChild @ converse.js:30983
_dataRecv @ converse.js:33263
_onRequestStateChange @ converse.js:34972
XMLHttpRequest.send (async)
sendFunc @ converse.js:35075
_processRequest @ converse.js:35090
_throttledRequestHandler @ converse.js:35236
_onIdle @ converse.js:34869
_onIdle @ converse.js:33897
(anonymous) @ converse.js:33903
setTimeout (async)
_onIdle @ converse.js:33902
(anonymous) @ converse.js:33903
setTimeout (async)
_onIdle @ converse.js:33902
(anonymous) @ converse.js:33903
converse.js:39333  FATAL: error: Cannot read property 'getAttribute' of null

```

**Comment by jcbrand** [comment]
Thanks, should be fixed in the next release.
