### ISSUE TITLE
Call to registerRosterXHandler and registerPresenceHandler on onReconnected give exception

### ISSUE THREAD

**Issue by nevcos** [jcbrand/converse.js#406]
When "onReconnected" is called after a reconnect, the following uncaught exception is triggered:

```
User connection callback caused an exception: TypeError: this.registerRosterXHandler is not a function TypeError: this.registerRosterXHandler is not a function
    at Object.<anonymous> (chrome-extension://mmpbhbnfanjidacnlnkobgpeodpeogpd/vendor/converse-0.9.3/converse-no-locales-no-otr.js:27697:22)
    at jQuery.extend.proxy.proxy (chrome-extension://mmpbhbnfanjidacnlnkobgpeodpeogpd/vendor/converse-0.9.3/converse-no-locales-no-otr.js:989:14)
    at Object._.extend.fetch.options.success (chrome-extension://mmpbhbnfanjidacnlnkobgpeodpeogpd/vendor/converse-0.9.3/converse-no-locales-no-otr.js:24161:22)
    at Backbone.BrowserStorage.sync.Backbone.localSync (chrome-extension://mmpbhbnfanjidacnlnkobgpeodpeogpd/vendor/converse-0.9.3/converse-no-locales-no-otr.js:25563:17)
    at Backbone.sync (chrome-extension://mmpbhbnfanjidacnlnkobgpeodpeogpd/vendor/converse-0.9.3/converse-no-locales-no-otr.js:25604:40)
    at _.extend.sync (chrome-extension://mmpbhbnfanjidacnlnkobgpeodpeogpd/vendor/converse-0.9.3/converse-no-locales-no-otr.js:24011:28)
    at _.extend.fetch (chrome-extension://mmpbhbnfanjidacnlnkobgpeodpeogpd/vendor/converse-0.9.3/converse-no-locales-no-otr.js:24165:19)
    at Object.converse.initialize.initStatus (chrome-extension://mmpbhbnfanjidacnlnkobgpeodpeogpd/vendor/converse-0.9.3/converse-no-locales-no-otr.js:27609:29)
    at Object.converse.initialize.onReconnected (chrome-extension://mmpbhbnfanjidacnlnkobgpeodpeogpd/vendor/converse-0.9.3/converse-no-locales-no-otr.js:27693:18)
    at Object.converse.initialize.onConnect (chrome-extension://mmpbhbnfanjidacnlnkobgpeodpeogpd/vendor/converse-0.9.3/converse-no-locales-no-otr.js:27533:30)
```

I think that those functions should be called on rosterview:

```
this.onReconnected = function () {
  this.initStatus($.proxy(function () {
    this.rosterview.registerRosterXHandler();
    this.rosterview.registerPresenceHandler();
```

Using converse 0.9.3 (converse-no-locales-no-otr.js file) with Chrome 43 on Windows 7.

**Comment by jcbrand** [comment]
Thanks @nevocs, it should be fixed now.
