### ISSUE TITLE
closeAllChatBoxes is giving ReferenceError when 2 chats are open

### ISSUE THREAD

**Issue by nevcos** [jcbrand/converse.js#415]
When logging out, the closeAllChatBoxes function is called, and when there are more than 1 chatbox open, the following error appears on console:

```
TypeError: Cannot read property 'get' of undefined
    at null.<anonymous> (converse-0.9.3/converse-no-locales-no-otr.js:30337:35)
    at jQuery.extend.proxy.proxy (converse-0.9.3/converse-no-locales-no-otr.js:989:14)
    at Function._.each._.forEach (converse-0.9.3/converse-no-locales-no-otr.js:11320:9)
    at _.each.Collection.(anonymous function) [as each] (converse-0.9.3/converse-no-locales-no-otr.js:24691:24)
    at converse.initialize.ChatBoxViews.Backbone.Overview.extend.closeAllChatBoxes (converse-0.9.3/converse-no-locales-no-otr.js:30336:28)
    at Object.converse.initialize.logOut (converse-0.9.3/converse-no-locales-no-otr.js:27645:35)
```

I think the problem is that you are removing sub-elements of the model inside a each statement.
I've done this fix and it's working:

```
// Replaced this:

this.model.each($.proxy(function (model) {
    var id = model.get('id'); // Error here, model is null
    if (include_controlbox || id !== 'controlbox') {
        if (this.get(id)) { // Should always resolve, but shit happens
            this.get(id).close();
        }
    }
}, this));

// By:

var ids = [];

this.model.each(function (model) {
	var id = model.get('id');
	if (include_controlbox || id !== 'controlbox') {
		ids.push(id);
	}
});

ids.forEach(function(id) {					
	var chatbox = this.get(id);
	if (chatbox) chatbox.close();
}, this);
```

Using converse 0.9.3 (converse-no-locales-no-otr.js file) with Chrome 43 on Windows 7.

Thanks

**Comment by jcbrand** [comment]
Thanks for the bug report and the solution. Should be fixed now. See the relevant commit.
