### ISSUE TITLE
Build: Conver.js throwing error

### ISSUE THREAD

**Issue by sinsharat** [jcbrand/converse.js#859]
While trying to build converse.js in linux machine getting the below error:
```
npm http 200 http://registry.npmjs.org/configstore/-/configstore-2.1.0.tgz
npm ERR! Error: ENOENT, lstat '/home/sharat/gowork/src/github.com/jcbrand/converse.js/node_modules/snyk/node_modules/request/node_modules/http-signature/node_modules/sshpk/node_modules/tweetnacl/nacl.min.js'
npm ERR! If you need help, you may report this log at:
npm ERR!     <http://github.com/isaacs/npm/issues>
npm ERR! or email it to:
npm ERR!     <npm-@googlegroups.com>

npm ERR! System Linux 3.13.0-24-generic
npm ERR! command "/usr/bin/nodejs" "/usr/bin/npm" "install"
npm ERR! cwd /home/sharat/gowork/src/github.com/jcbrand/converse.js
npm ERR! node -v v0.10.25
npm ERR! npm -v 1.3.10
npm ERR! path /home/sharat/gowork/src/github.com/jcbrand/converse.js/node_modules/snyk/node_modules/request/node_modules/http-signature/node_modules/sshpk/node_modules/tweetnacl/nacl.min.js
npm ERR! fstream_path /home/sharat/gowork/src/github.com/jcbrand/converse.js/node_modules/snyk/node_modules/request/node_modules/http-signature/node_modules/sshpk/node_modules/tweetnacl/nacl.min.js
npm ERR! fstream_type File
npm ERR! fstream_class FileWriter
npm ERR! code ENOENT
npm ERR! errno 34
npm ERR! fstream_stack /usr/lib/nodejs/fstream/lib/writer.js:284:26
npm ERR! fstream_stack Object.oncomplete (fs.js:107:15)
npm http 200 http://registry.npmjs.org/latest-version/-/latest-version-2.0.0.tgz
npm http 200 http://registry.npmjs.org/boxen/-/boxen-0.3.1.tgz
npm http 200 http://registry.npmjs.org/get-caller-file/-/get-caller-file-1.0.2.tgz
npm http 200 http://registry.npmjs.org/cliui/-/cliui-3.2.0.tgz
npm http 200 http://registry.npmjs.org/set-blocking/-/set-blocking-2.0.0.tgz
npm ERR! Error: ENOENT, lstat '/home/sharat/gowork/src/github.com/jcbrand/converse.js/node_modules/snyk/node_modules/inquirer/node_modules/rx/dist/rx.min.js'
npm ERR! If you need help, you may report this log at:
npm ERR!     <http://github.com/isaacs/npm/issues>
npm ERR! or email it to:
npm ERR!     <npm-@googlegroups.com>

npm ERR! System Linux 3.13.0-24-generic
npm ERR! command "/usr/bin/nodejs" "/usr/bin/npm" "install"
npm ERR! cwd /home/sharat/gowork/src/github.com/jcbrand/converse.js
npm ERR! node -v v0.10.25
npm ERR! npm -v 1.3.10
npm ERR! path /home/sharat/gowork/src/github.com/jcbrand/converse.js/node_modules/snyk/node_modules/inquirer/node_modules/rx/dist/rx.min.js
npm ERR! fstream_path /home/sharat/gowork/src/github.com/jcbrand/converse.js/node_modules/snyk/node_modules/inquirer/node_modules/rx/dist/rx.min.js
npm ERR! fstream_type File
npm ERR! fstream_class FileWriter
npm ERR! code ENOENT
npm ERR! errno 34
npm ERR! fstream_stack /usr/lib/nodejs/fstream/lib/writer.js:284:26
npm ERR! fstream_stack Object.oncomplete (fs.js:107:15)
npm http 200 http://registry.npmjs.org/os-locale/-/os-locale-1.4.0.tgz
npm http 200 http://registry.npmjs.org/lodash.assign/-/lodash.assign-4.2.0.tgz
npm http 200 http://registry.npmjs.org/window-size/-/window-size-0.2.0.tgz
npm http 200 http://registry.npmjs.org/require-main-filename/-/require-main-filename-1.0.1.tgz
npm http 200 http://registry.npmjs.org/require-directory/-/require-directory-2.1.1.tgz
npm http 200 http://registry.npmjs.org/which-module/-/which-module-1.0.0.tgz
npm http 200 http://registry.npmjs.org/y18n/-/y18n-3.2.1.tgz
npm http 304 http://registry.npmjs.org/is-finite
npm http 200 http://registry.npmjs.org/is-path-inside/-/is-path-inside-1.0.0.tgz
npm http 200 http://registry.npmjs.org/yargs-parser/-/yargs-parser-2.4.1.tgz
npm http 200 http://registry.npmjs.org/arrify/-/arrify-1.0.1.tgz
npm ERR! error rolling back Error: ENOTEMPTY, rmdir '/home/sharat/gowork/src/github.com/jcbrand/converse.js/node_modules/eslint/node_modules/escope/node_modules/es6-weak-map/node_modules/es5-ext/test/array'
npm ERR! error rolling back  eslint@3.19.0 { [Error: ENOTEMPTY, rmdir '/home/sharat/gowork/src/github.com/jcbrand/converse.js/node_modules/eslint/node_modules/escope/node_modules/es6-weak-map/node_modules/es5-ext/test/array']
npm ERR! error rolling back   errno: 53,
npm ERR! error rolling back   code: 'ENOTEMPTY',
npm ERR! error rolling back   path: '/home/sharat/gowork/src/github.com/jcbrand/converse.js/node_modules/eslint/node_modules/escope/node_modules/es6-weak-map/node_modules/es5-ext/test/array' }
npm http 304 http://registry.npmjs.org/restore-cursor
npm http 304 http://registry.npmjs.org/code-point-at
npm http 304 http://registry.npmjs.org/is-fullwidth-code-point
npm http 200 http://registry.npmjs.org/rc/-/rc-1.2.1.tgz
npm http GET http://registry.npmjs.org/number-is-nan
npm http 200 http://registry.npmjs.org/is-promise
npm http GET http://registry.npmjs.org/is-promise/-/is-promise-2.1.0.tgz
npm http 304 http://registry.npmjs.org/escape-string-regexp
npm http 304 http://registry.npmjs.org/object-assign
npm http 200 http://registry.npmjs.org/infinity-agent/-/infinity-agent-2.0.3.tgz
npm http 200 http://registry.npmjs.org/array-union/-/array-union-1.0.2.tgz
npm http 200 http://registry.npmjs.org/lowercase-keys/-/lowercase-keys-1.0.0.tgz
npm http 200 http://registry.npmjs.org/nested-error-stacks/-/nested-error-stacks-1.0.2.tgz
npm http 200 http://registry.npmjs.org/duplexify/-/duplexify-3.5.0.tgz
npm http 200 http://registry.npmjs.org/prepend-http/-/prepend-http-1.0.4.tgz
npm http 200 http://registry.npmjs.org/is-redirect/-/is-redirect-1.0.0.tgz
npm http 200 http://registry.npmjs.org/object-assign/-/object-assign-3.0.0.tgz
npm http 200 http://registry.npmjs.org/timed-out/-/timed-out-2.0.0.tgz
npm http 200 http://registry.npmjs.org/read-all-stream/-/read-all-stream-3.1.0.tgz
npm http 304 http://registry.npmjs.org/number-is-nan
npm http 200 http://registry.npmjs.org/is-promise/-/is-promise-2.1.0.tgz
npm ERR!
npm ERR! Additional logging details can be found in:
npm ERR!     /home/sharat/gowork/src/github.com/jcbrand/converse.js/npm-debug.log
npm ERR! not ok code 0
make: *** [stamp-npm] Error 1
```
I am behind proxy, but i think i have done the necessary changes for it since other packages are downloading fine.

**Comment by sinsharat** [comment]
I think its problem with using git:
```
1101 info maybeGithub Attempting requirejs/text#2.0.15 from git://github.com/requirejs/text#2.0.15
1102 silly lockFile 192f668a-github-com-requirejs-text-2-0-15 git://github.com/requirejs/text#2.0.15
1103 verbose lock git://github.com/requirejs/text#2.0.15 /home/sharat/.npm/192f668a-github-com-requirejs-text-2-0-15.lock
1104 verbose addRemoteGit [ 'git://github.com/requirejs/text', '2.0.15' ]
1105 verbose git clone git://github.com/requirejs/text Cloning into bare repository '/home/sharat/.npm/_git-remotes/git-github-com-requirejs-text-20b46444'...
1105 verbose git clone git://github.com/requirejs/text fatal: unable to connect to github.com:
1105 verbose git clone git://github.com/requirejs/text github.com[0: 192.30.255.112]: errno=Connection timed out
1105 verbose git clone git://github.com/requirejs/text github.com[1: 192.30.255.113]: errno=Connection timed out
1106 silly lockFile 20b46444-git-github-com-requirejs-text git://github.com/requirejs/text
1107 info maybeGithub Attempting requirejs/text#2.0.15 from git+ssh://git@github.com:requirejs/text#2.0.15
1108 silly lockFile 0d39057f-github-com-requirejs-text-2-0-15 git+ssh://git@github.com:requirejs/text#2.0.15
1109 verbose lock git+ssh://git@github.com:requirejs/text#2.0.15 /home/sharat/.npm/0d39057f-github-com-requirejs-text-2-0-15.lock
1110 verbose addRemoteGit [ 'git@github.com:requirejs/text', '2.0.15' ]
1111 verbose git clone git@github.com:requirejs/text Cloning into bare repository '/home/sharat/.npm/_git-remotes/git-github-com-requirejs-text-f62dc3cf'...
1111 verbose git clone git@github.com:requirejs/text ssh: connect to host github.com port 22: Connection timed out
1111 verbose git clone git@github.com:requirejs/text fatal: Could not read from remote repository.
1111 verbose git clone git@github.com:requirejs/text
1111 verbose git clone git@github.com:requirejs/text Please make sure you have the correct access rights
1111 verbose git clone git@github.com:requirejs/text and the repository exists.
1112 silly lockFile f62dc3cf-git-github-com-requirejs-text git@github.com:requirejs/text
1113 silly lockFile 26f8c8c9-text-requirejs-text-2-0-15 text@requirejs/text#2.0.15
1114 silly lockFile 26f8c8c9-text-requirejs-text-2-0-15 text@requirejs/text#2.0.15
1115 error Error: No compatible version found: text@'requirejs/text#2.0.15'
1115 error Valid install targets:
1115 error ["0.1.0"]
1115 error     at installTargetsError (/usr/share/npm/lib/cache.js:719:10)
1115 error     at /usr/share/npm/lib/cache.js:638:10
1115 error     at saved (/usr/share/npm/node_modules/npm-registry-client/lib/get.js:142:7)
1115 error     at /usr/lib/nodejs/graceful-fs/polyfills.js:133:7
1115 error     at Object.oncomplete (fs.js:107:15)
1116 error If you need help, you may report this log at:
1116 error     <http://github.com/isaacs/npm/issues>
1116 error or email it to:
1116 error     <npm-@googlegroups.com>
1117 error System Linux 3.13.0-24-generic
1118 error command "/usr/bin/nodejs" "/usr/bin/npm" "install"
1119 error cwd /home/sharat/gowork/src/github.com/jcbrand/converse.js
1120 error node -v v0.10.25
1121 error npm -v 1.3.10
1122 verbose exit [ 1, true ]
```
