### ISSUE TITLE
Inverse/Configuration : FATAL error when visible_toolbar_buttons.emoji = false

### ISSUE THREAD

**Issue by darkcosmos** [jcbrand/converse.js#921]
Hello,

I was playing with the configuration of inverse when i found this issue : 
```
FATAL: TypeError: Cannot set property 'innerHTML' of null
    at child.renderToolbar (http://localhost:88/XmppClient/webjars/converse/3.2.1/inverse.js:53501:38)
    at child.renderChatArea (http://localhost:88/XmppClient/webjars/converse/3.2.1/inverse.js:59225:30)
    at child.render (http://localhost:88/XmppClient/webjars/converse/3.2.1/inverse.js:59202:26)
    at child.render (http://localhost:88/XmppClient/webjars/converse/3.2.1/inverse.js:62470:56)
    at child.wrappedOverride (http://localhost:88/XmppClient/webjars/converse/3.2.1/inverse.js:45447:26)
    at apply (http://localhost:88/XmppClient/webjars/converse/3.2.1/inverse.js:4262:17)
    at child.wrapper [as render] (http://localhost:88/XmppClient/webjars/converse/3.2.1/inverse.js:9119:16)
    at child.initialize (http://localhost:88/XmppClient/webjars/converse/3.2.1/inverse.js:59183:26)
    at child.initialize (http://localhost:88/XmppClient/webjars/converse/3.2.1/inverse.js:61508:47)
    at child.wrappedOverride (http://localhost:88/XmppClient/webjars/converse/3.2.1/inverse.js:45447:26)
```

It occurs when i deactivate the emoji visibility in my configuration : 
```
visible_toolbar_buttons :{
   call: false,
   clear: false,
   emoji: false,
   toggle_occupants: true
}
```

**Comment by jcbrand** [comment]
Thanks for the bug report. Will take a look.
